---
abstract: 'Dist::Zilla Releaser plugin for uploading to CPAN::Site mirror.'
author:
  - 'Stephen Cardie <stephenca@ls26.net>'
build_requires:
  Capture::Tiny: 0
  File::Temp: 0
  Test::More: 0.88
  blib: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-UploadToCpanSite
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dist::Zilla::Plugin::UploadToCpanSite:
    file: lib/Dist/Zilla/Plugin/UploadToCpanSite.pm
    version: 1.132210
requires:
  Dist::Zilla: 4.3
  Dist::Zilla::Role::Releaser: 0
  English: 0
  File::Spec: 0
  Moose: 0
  MooseX::Has::Sugar: 0
  MooseX::Types::Moose: 0
  Net::SCP: 0
  Net::SSH: 0
  Try::Tiny: 0
  common::sense: 0
  namespace::autoclean: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-UploadToCpanSite
version: 1.132210
